version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
             docker-compose -f docker-compose-build.yaml build --parallel
      - deploy:
          name: Tag and Push application Docker image
          command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag udagram-api-feed shifo/udagram-api-feed:v1
              docker tag udagram-api-user shifo/udagram-api-user:v1
              docker tag udagram-frontend shifo/udagram-frontend:v1
              docker tag reverseproxy shifo/reverseproxy:v1
              docker push shifo/udagram-api-feed:v1
              docker push shifo/udagram-api-user:v1
              docker push shifo/udagram-frontend:v1
              docker push shifo/reverseproxy:v1
            